### ISSUE TITLE
Reverse display

### ISSUE THREAD

**Issue by mayalex** [DavidTre07/Marlin-Configurations#1]
Hello @DavidTre07! Perhaps, can you help me?
I used your config and got reverse display, but a touch works without reverse. (Stock Printer 2019 QQ-S)
Have been this experience?
![image](https://user-images.githubusercontent.com/4323742/99611797-65805d80-2a25-11eb-818e-841d6be9a46c.png)

Thanks!

**Comment by DavidTre07** [comment]
Hello @mayalex , I don't know how to solve this issue.
I remember a old commit form Anders Sahlman on his repo about this problem but I don't know if it has been merged in Marlin.
You can check here: https://github.com/AndersSahlman/Marlin/commit/7eed139608c5388aa849a639d0142308d55b37ee
Perhaps he can drive you to the right direction.

Sorry not be very helpfull !

**Comment by mayalex** [comment]
Hello @DavidTre07!
Thanks) 
I solved this problem, added TFT_ROTATION with value:
`#define TFT_ROTATION TFT_ROTATE_180_MIRROR_Y`
`#define TFT_ROTATION TFT_ROTATE_180_MIRROR_X`
